[package]
authors = ["Shinyzenith <aakashsensharma@gmail.com>"]
edition = "2021"
name = "wayout"
version = "1.0.0"

[dependencies]
clap = "3.1.2"
smithay-client-toolkit = "0.15.3"

[[bin]]
name = "wayout"
path = "src/wayout.rs"
